---
kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build  
  environment:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  commands:
  - ln -s /Users/$${USER}/Library $${HOME}/Library
  - fastlane adhoc

trigger:
  branch:
  - master
