---
kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build  
  environment:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
    PASSWORD:
      from_secret: keychain_password
  commands:
  - HOME_ORIG=`echo ~$${USER}`
  - echo $HOME_ORIG
#  - ln -s `echo ~$${HOME_ORIG}/Library $${HOME}/Library
  - security list-keychains
#  - security login-keychain -s "/Users/hypafrag/Library/Keychains/login.keychain-db" || true
#  - security list-keychains
#  - security login-keychain
#  - security unlock-keychain -p $${PASSWORD} "/Users/hypafrag/Library/Keychains/login.keychain-db"
#  - security list-keychains
#  - fastlane adhoc

trigger:
  branch:
  - master
