---
kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build  
  environment:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
    WEBDAV_USER:
      from_secret: WEBDAV_USER
  commands:
  - fastlane adhoc
  - ARTIFACT_DIR=/tmp/$${DRONE_BUILD_STARTED}_$${CI_COMMIT_SHA}
  - echo $${ARTIFACT_DIR}
  - curl -s -X MKCOL https://webdav.coons.club/$${ARTIFACT_DIR} --user $${WEBDAV_USER}
  - curl -s -T 'herald.ipa' https://webdav.coons.club/$${ARTIFACT_DIR}/herald.ipa --user $${WEBDAV_USER}

trigger:
  branch:
  - master
