---
kind: pipeline
type: exec
name: default

platform:
  os: darwin

steps:
- name: build  
  environment:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
    PASSWORD:
      from_secret: keychain_password
  commands:
  - security list-keychains
  - security -v unlock-keychain -p $${PASSWORD} "/Users/hypafrag/Library/Keychains/login.keychain-db"
  - security list-keychains
  - fastlane adhoc

trigger:
  branch:
  - master
