#!/bin/sh

x1=$(($1*1))
x2=$(($1*2))
x3=$(($1*3))

inkscape -z -e /Users/valera/Desktop/icons/${x1}x${x1}.png -w ${x1} -h ${x1} -b ffffffff /Users/valera/Desktop/icons/herald.svg
inkscape -z -e /Users/valera/Desktop/icons/${x2}x${x2}.png -w ${x2} -h ${x2} -b ffffffff /Users/valera/Desktop/icons/herald.svg
inkscape -z -e /Users/valera/Desktop/icons/${x3}x${x3}.png -w ${x3} -h ${x3} -b ffffffff /Users/valera/Desktop/icons/herald.svg
