# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace: "herald.xcworkspace",
      scheme: "herald",
      export_xcargs: "-allowProvisioningUpdates",
      derived_data_path: "build",
      build_path: "build"
    )
    upload_to_testflight
  end

  desc "Build AdHoc"
  lane :adhoc do
    build_app(
      workspace: "herald.xcworkspace",
      scheme: "herald",
      export_method: "ad-hoc",
      export_xcargs: "-allowProvisioningUpdates",
      derived_data_path: "build",
      build_path: "build"
    )
  end
end
